### ISSUE TITLE
Empty button in story

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/hub#102]
Probably related to #86 

![screen_shot_2015-03-28_at_10 56 04_am](https://cloud.githubusercontent.com/assets/2538465/6882189/9bf14dd0-d539-11e4-85de-b2014dd8aa23.png)

**Comment by sachalifs** [comment]
Fixed in https://github.com/DemocracyOS/hub/commit/7553508e49c7b95561835a856f5535b3e22cf41b
