### ISSUE TITLE
Redirect to DemocracyOS instance

### ISSUE THREAD

**Issue by sachalifs** [DemocracyOS/hub#17]
As per this first Demo of platform, it should have a config variable (env variable as well) pointing to a DemocracyOS instance URL.

After performing login/signup on platform, user should be redirected to this URL (that would be their own instance in the future)

**Comment by jfresco** [comment]
Done in [b6f345a](https://github.com/DemocracyOS/platform/commit/b6f345ac4b8c4ecc44a22ae5eab4e6d9f8a1b2dc)
