### ISSUE TITLE
Fast switch between Platform and DemocracyOS instance

### ISSUE THREAD

**Issue by sachalifs** [DemocracyOS/hub#19]
See if somehow we can avoid a blank page between platform and DemocracyOS after the login process

**Comment by vmariano** [comment]
We should investigate some techniques to do this and if is possible.

**Comment by gvilarino** [comment]
I'd be happy to see if the switch is fast; even if it entails a blank screen atm.

**Comment by jfresco** [comment]
I think the best way to do this is by modifying the `window.location` property while showing a fancy transition page.
Other approach could be using `IFRAME`s.

**Comment by gvilarino** [comment]
This is sort of eye-candy. Let's worry about this once we've done everything else.

**Comment by mjlescano** [comment]
A fast approach, but 100% perceived speed, is to imeplement a progress bar like [Nprogress](http://ricostacruz.com/nprogress/).

The why would work: https://blog.kissmetrics.com/the-progress-bar/

**Comment by sachalifs** [comment]
I closed this issue because it was regarding the `different domain` vs `subdomain` and the session between both apps, which we solved using JWT
