### ISSUE TITLE
Update styles of login/logout

### ISSUE THREAD

**Issue by vmariano** [DemocracyOS/hub#21]
There are some top icons should be see like of DOS like login, for example:
![icon](https://cloud.githubusercontent.com/assets/796960/5782449/b2a9442e-9d99-11e4-85d2-ee759dc1c575.png)

**Comment by jfresco** [comment]
Some elements in the form are no properly aligned; e.g., _Forgot password?_ should be next to _Password_, not under it.

![image](https://cloud.githubusercontent.com/assets/4335188/5900577/9f259fee-a549-11e4-882e-b53b232d9be4.png)

Also, elements look too wide in comparison with `democracyos/app`.
