### ISSUE TITLE
Change font face

### ISSUE THREAD

**Issue by vmariano** [DemocracyOS/hub#23]

**Comment by jfresco** [comment]
Team,
I chose five fonts from [Google Fonts](https://www.google.com/fonts). Here are some screenshots. Please let me know which one seems more proper to you or suggest me other one.

You can try them by running the code in this branch and changing [this line](https://github.com/DemocracyOS/platform/blob/feature/fonts/lib/boot/index.styl#L7) with the name of the desired font (you can change it also from your browser's Developer Console).

Open Sans:
![image](https://cloud.githubusercontent.com/assets/4335188/5901182/2ec2bd6c-a54f-11e4-9c8c-7a3204450767.png)

Lato:
![image](https://cloud.githubusercontent.com/assets/4335188/5901165/019d9884-a54f-11e4-8a65-bf464025902f.png)

Oxygen:
![image](https://cloud.githubusercontent.com/assets/4335188/5901212/7256dbbc-a54f-11e4-84b5-0f7f7b616599.png)

Maven Pro:
![image](https://cloud.githubusercontent.com/assets/4335188/5901246/a6696e74-a54f-11e4-8223-551dc0a2b18c.png)

Karla:
![image](https://cloud.githubusercontent.com/assets/4335188/5901261/c154d93a-a54f-11e4-8232-c662420343b0.png)

cc: @gvilarino
