### ISSUE TITLE
Build process is not installing new components if components directory exists

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/hub#31]
When you run `make` and you already have a `components` directory (for example, you added a new component and you wish the build chain install it), the build process does not execute `component install`. You have to run `component install` by hand.

**Comment by gvilarino** [comment]
I believe the approach is to `make clean && make` for these cases. It's something to look into the updated build process. I think I recall there was one good reason why we didn't change this, but we can definitely look at it again.

**Comment by jfresco** [comment]
The bug is in the Makefile. Target `component` is not PHONY, so is executed only when `components` directory does not exist. The same happens with `node_modules` target.
I think it's an counterintuitive approach; I can't find a reason for expecting a developer execute a `make clean` when she adds a component or a npm module.
As `component install` and `npm install` installs the modules that don't exists, we should mantain that approach.
