### ISSUE TITLE
Fix error handling on instance API

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/hub#46]
Found two cases where errors are incorrectly handled:
- When user already has an instance and tries to create one, the form shows an error, the app crashed and the instances is created anyway
- When a user tries to create an instance with a URL already in use the form dumps a mongoDB error and the app crashes.

We have to handle properly those errors.

**Comment by gvilarino** [comment]
I belive a quickfix would do, but we should agree on an aproach for `app` and replicate here as a final solution.

**Comment by jfresco** [comment]
Agreed.
