### ISSUE TITLE
Add image cropping support

### ISSUE THREAD

**Issue by jfresco** [DemocracyOS/hub#49]
Put a widget on `/instance/new` in order to let the user crop the referenced image.
Note that the image cannot be uploaded nor modified; we can just save crop coordinates data. Besides, the pages that displays the images should be smart enough to display just the cropped area. 
Maybe we can use [yields/crop](https://github.com/yields/crop/).

**Comment by gvilarino** [comment]
Would that go into the `LOGO` env var?

**Comment by jfresco** [comment]
Not really. I thought in a picture instead of a logo:
![image](https://cloud.githubusercontent.com/assets/4335188/6028140/fa4b6fac-abc5-11e4-816e-1ba557ee4063.png)

**Comment by gvilarino** [comment]
This can also work for user avatars under `settings`
