### ISSUE TITLE
Default story layout

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/hub#60]
I created a `law` with 3 1-line paragraps and a picutre, and it looks like this:

![dsgvgtevvc](https://cloud.githubusercontent.com/assets/2538465/6589458/9d896888-c75d-11e4-95a0-ed825331f3c2.png)

There should be some sort of constraint to the picture size (make it match what's in [the design proposal](http://democracyos.webflow.com/newsfeed)) as much as possible.

Also, some truncation to texts beyond 5 lines.

**Comment by sachalifs** [comment]
Still have to truncate text to a maximum of 5 lines
