### ISSUE TITLE
Session isn't being shared with deployments

### ISSUE THREAD

**Issue by gvilarino** [DemocracyOS/hub#70]
Repro:
1. Have a democracy
2. Open an incognito or clean browser
3. Go to `hub`
4. Log in
5. Click on the link to your democracy
6. Se that you're logged out.

On addition, if you click sign-in, you're thrown back to `hub` where you _are_ signed in.

Expected behavior: if I sign in somewhere, I should be signed in anywhere under the same domain.

**Comment by sachalifs** [comment]
it was an env variables issue
